// Compiles admin/dashboard.html into src/admin-html.generated.js so the Worker
// can serve the dashboard for every tenant from its bundle. Run before deploy.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const html = readFileSync(join(root, "admin", "dashboard.html"), "utf8");

const out = `// AUTO-GENERATED by scripts/build-worker.mjs — do not edit by hand.\nexport const ADMIN_HTML = ${JSON.stringify(html)};\n`;
writeFileSync(join(root, "src", "admin-html.generated.js"), out);

console.log(`Bundled admin dashboard (${html.length} bytes) into src/admin-html.generated.js`);
