// Bundles admin/dashboard.html into dist/_worker.js for Cloudflare Pages.
// Also copies landing/index.html as static fallback.
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(root, "dist");
mkdirSync(dist, { recursive: true });

// Read sources
const html = readFileSync(join(root, "admin", "dashboard.html"), "utf8");
const workerSrc = readFileSync(join(root, "src", "worker.js"), "utf8");

// Inline admin dashboard HTML into worker
const inlinedHtml = "// AUTO-GENERATED by scripts/build-worker.mjs\n"
  + "export const ADMIN_HTML = " + JSON.stringify(html) + ";\n";

const bundle = workerSrc.replace(
  /^import\s*\{[^}]*ADMIN_HTML[^}]*\}\s*from\s*['"]\.\/admin-html\.generated\.js['"];?\s*\n?/m,
  inlinedHtml + "\n"
);

writeFileSync(join(dist, "_worker.js"), bundle);

// Copy landing page as static file
const landingSrc = join(root, "landing", "index.html");
try {
  copyFileSync(landingSrc, join(dist, "index.html"));
  console.log("Copied landing/index.html -> dist/index.html");
} catch (e) {
  console.warn("landing/index.html not found, skipping");
}

console.log("Built dist/_worker.js (" + bundle.length + " bytes)");
