// Bundles admin/dashboard.html + landing/index.html + src/worker.js into dist/_worker.js
// for Cloudflare Pages deployment. Both HTML files are inlined into the worker bundle
// because the Pages API deployment path does not support env.ASSETS.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(root, "dist");
mkdirSync(dist, { recursive: true });

// 1. Read all source files
const adminHtml = readFileSync(join(root, "admin", "dashboard.html"), "utf8");
const landingHtml = readFileSync(join(root, "landing", "index.html"), "utf8");
const workerSrc = readFileSync(join(root, "src", "worker.js"), "utf8");

// 2. Build the inlined exports
const inlinedBlock = `// AUTO-GENERATED by scripts/build-worker.mjs — do not edit by hand.
export const ADMIN_HTML = ${JSON.stringify(adminHtml)};
export const LANDING_HTML = ${JSON.stringify(landingHtml)};
`;

const bundle = workerSrc.replace(
  /^import\s*\{[^}]*ADMIN_HTML[^}]*\}\s*from\s*['"]\.\/admin-html\.generated\.js['"];?\s*\n?/m,
  inlinedBlock + "\n",
);

writeFileSync(join(dist, "_worker.js"), bundle);

// Also publish the plain landing HTML so the build output dir always
// contains a static index.html alongside the worker (Pages builds expect
// at least one static asset; the worker serves LANDING_HTML inline anyway).
writeFileSync(join(dist, "index.html"), landingHtml);

console.log(`Built dist/_worker.js (${bundle.length} bytes) + dist/index.html — ready for wrangler pages deploy`);
