"""Client config + lead store. File-backed source of truth on the VPS.

Layout (relative to LAZUSAI_DATA_DIR, default ./data):
  clients/<client_id>.json     tenant config
  clients/index.json           routing index (identifier -> client_id)
  leads/<client_id>/leads.json append-only lead log
"""
from __future__ import annotations

import json
import os
import re
import time
from pathlib import Path

DATA_DIR = Path(os.environ.get("LAZUSAI_DATA_DIR", "data"))
CLIENTS_DIR = DATA_DIR / "clients"
LEADS_DIR = DATA_DIR / "leads"

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def slugify(name: str) -> str:
    slug = _SLUG_RE.sub("-", name.lower()).strip("-")
    return slug[:50] or "client"


def client_path(client_id: str) -> Path:
    return CLIENTS_DIR / f"{client_id}.json"


def load_client(client_id: str) -> dict:
    path = client_path(client_id)
    if not path.exists():
        raise FileNotFoundError(f"No config for client_id={client_id}")
    return json.loads(path.read_text())


def save_client(config: dict) -> Path:
    CLIENTS_DIR.mkdir(parents=True, exist_ok=True)
    config["updated_at"] = _now()
    path = client_path(config["client_id"])
    path.write_text(json.dumps(config, indent=2))
    rebuild_index()
    return path


def list_clients(active_only: bool = False) -> list[dict]:
    if not CLIENTS_DIR.exists():
        return []
    out = []
    for p in sorted(CLIENTS_DIR.glob("*.json")):
        if p.name in ("_schema.json", "index.json"):
            continue
        cfg = json.loads(p.read_text())
        if active_only and not cfg.get("active", True):
            continue
        out.append(cfg)
    return out


def unique_client_id(base: str) -> str:
    cid = slugify(base)
    candidate = cid
    n = 2
    while client_path(candidate).exists():
        candidate = f"{cid}-{n}"
        n += 1
    return candidate


def rebuild_index() -> dict:
    """Regenerate clients/index.json from all client configs."""
    routes: dict[str, str] = {}
    ids: list[str] = []
    for cfg in list_clients():
        cid = cfg["client_id"]
        ids.append(cid)
        for key in (cfg.get("apple_id_number"), cfg.get("bluebubbles_chat_guid")):
            if key:
                routes[key] = cid
    index = {
        "_comment": "Auto-generated by clients.rebuild_index(). Maps inbound identifiers to client_id.",
        "routes": routes,
        "clients": ids,
    }
    CLIENTS_DIR.mkdir(parents=True, exist_ok=True)
    (CLIENTS_DIR / "index.json").write_text(json.dumps(index, indent=2))
    return index


def append_lead(client_id: str, lead: dict) -> Path:
    """Append a lead to leads/<client_id>/leads.json (creating it)."""
    d = LEADS_DIR / client_id
    d.mkdir(parents=True, exist_ok=True)
    path = d / "leads.json"
    leads = []
    if path.exists():
        try:
            leads = json.loads(path.read_text())
        except json.JSONDecodeError:
            leads = []
    lead = {"captured_at": _now(), **lead}
    leads.append(lead)
    path.write_text(json.dumps(leads, indent=2))
    return path


def todays_leads(client_id: str) -> list[dict]:
    path = LEADS_DIR / client_id / "leads.json"
    if not path.exists():
        return []
    leads = json.loads(path.read_text())
    today = time.strftime("%Y-%m-%d")
    return [l for l in leads if str(l.get("captured_at", "")).startswith(today)]


def _now() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
